Allows overriding the backup script template
arillso/ansible.restic pull request #45
Opened 2021-04-23 23:19 UTC by gotmax23

Basically, this PR allows specifying a custom template for the backup script, so the user can customize it. In addition to #32, this PR would make the role more extendable and wouldn't add any extra complexity.

2021-04-28 22:06 UTC, gotmax23 commented
Ping @mleutenegger.

Again, this is just a simple change, but it will make the role more extendable.

Also, this is a workaround for [https://github.com/arillso/ansible.restic/pull/32](https://github.com/arillso/ansible.restic/pull/32) until that's properly implemented.

2021-04-29 16:16 UTC, mleutenegger requested changes
Looking good, Thanks for the PR! I have made a remark in the readme to add a direct link to the template file. This way, it would be easier to find the reference.

2021-04-29 16:16 UTC, mleutenegger commented on README.md
> +Restic stores data in repositories. You have to specify at least one repositorym
Introduced a Typo

2021-04-29 16:16 UTC, mleutenegger commented on README.md
> +By default, this role will use the Jinja template file located at `templates/restic_script_Linux.j2` to construct the backup script. However, if you wish to customize it further, you may override the
It would be nice to have a direct link here, so people won't have to navigate the role files 😬

2021-04-29 16:18 UTC, mleutenegger commented
I think this fits well as it would allow even the most complex things to be done without having to use a rigid template. As backup strategies are in most cases depending on the usecase, this option would allow much more flexibility.

2021-04-29 19:28 UTC, gotmax23 commented
> I think this fits well as it would allow even the most complex things to be done without having to use a rigid template. As backup strategies are in most cases depending on the usecase, this option would allow much more flexibility.

@mleutenegger Yeah, this was my thinking. I made the changes you requested, so this should be ready to merge.

2021-09-29 06:56 UTC, mleutenegger approved these changes

2021-09-29 06:57 UTC, mleutenegger commented
Looking good, merging now 👍

2021-09-29 06:58 UTC, merged